# Generated by Django 6.1.1 on 2026-09-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period', models.CharField(max_length=50)),
                ('productivity_rating', models.IntegerField(default=3)),
                ('quality_rating', models.IntegerField(default=3)),
                ('teamwork_rating', models.IntegerField(default=3)),
                ('communication_rating', models.IntegerField(default=3)),
                ('overall_rating', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('areas_for_improvement', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
    ]
